### ISSUE TITLE
Move nss-wrapper logic into dockerfile entry-point

### ISSUE THREAD

**Issue by erikerlandson** [radanalyticsio/openshift-spark#17]
I'm wondering if it would be cleaner to publish openshift-spark containers that did all the "nss-wrapper" goo in a custom entrypoint.   Then people using our containers could get it without having to worry about doing it themselves if they customized startup logic.

**Comment by mattf** [comment]
see https://github.com/radanalyticsio/openshift-spark/pull/18

**Comment by mattf** [comment]
'oc rsh' and 'oc exec' do not invoke the container's entrypoint.

recommendation from openshift team is to provide a command to manually run or try using the shell profile.

**Comment by erikerlandson** [comment]
That is disappointing.
I wonder if it would be possible to create `oshinko rsh` and `oshinko exec`, that would wrap the nss logic around the rsh and exec arguments.

`oshinko exec <args>`  ==>  `oc exec entrypoint.sh <args>`

**Comment by mattf** [comment]
i'm still of the belief that the way to address this is closer to the source. maybe not in hadoop itself but at least in spark.

**Comment by mattf** [comment]
#21 addresses this for the 'oc run' case. 'oc rsh' and 'oc exec' are still an issue.

we should simply always recommend 'oc run' instead of shelling into an existing container w/ rsh or exec.
