### ISSUE TITLE
Add S2I support to provide a way to add artifacts to the image

### ISSUE THREAD

**Issue by rimolive** [radanalyticsio/openshift-spark#36]
I need to add an artifact inside /opt/spark/jars (the Cassandra connector) but there's no way to do that if not extend the image to add a single file or rsync'ing the file directly to the pod. There should be a way to just build a new image with S2I to add the files needed for my customized cluster

**Comment by aneagoe** [comment]
I'm looking for a similar feature. I also need to add the Cassandra connector. There are a few options (from a pvc for the jars shared across workers to rsync) but there's nothing elegant.

**Comment by traskiloner** [comment]
We add a folder in our Git with artifacts.
When it clone the branch, get the code and artifacts.

**Comment by rimolive** [comment]
Since we have Image Completion tool (https://github.com/radanalyticsio/openshift-spark#image-completion) and it has S2i capabilities, we can close this issue. @elmiko any objections to this?

**Comment by rimolive** [comment]
Closing this issue as Image Completion tool added this feature.
