### ISSUE TITLE
python 3

### ISSUE THREAD

**Issue by mohsen84** [radanalyticsio/openshift-spark#51]
Can you please guid me on where I can find an instruction for having spark cluster with Python 3 in Openshift?

thanks

**Comment by elmiko** [comment]
hi @mohsen84 , thanks for bringing this up.

we don't currently have a python3 image for openshift, but we have done some experimental work in the past using a python3 image.

i think we will create a python3 branch for this repository and use some of that prior work to create an image. unfortunately i don't have a time frame for how long that will take.

would it be useful for you to have a document explaining how to enable python3?

**Comment by elmiko** [comment]
i am closing this issue as we have merged the py36 images into the master branch
