### ISSUE TITLE
S3 object storage connectors

### ISSUE THREAD

**Issue by ThatBeardedDude** [radanalyticsio/openshift-spark#60]
With growing interest in using object storage (ceph, aws, minio, etc.) via s3a/n api-s, rises the question of implementing those features into this image.

Will this (including the appropriate jars in this image) be a desired thing?

**Comment by rimolive** [comment]
@ThatBeardedDude, did you take a look at our [S3 Source Example](https://radanalytics.io/examples/s3-source-example) and [Ceph Source Example](https://radanalytics.io/examples/ceph-source-example)? Let us know if that's what you are talking about

**Comment by ThatBeardedDude** [comment]
I took a look at both, both failing at some point for some reason. The Ceph Nano (which was the more promising of the two, for me) failed as early as I got to set up the pod. It failed spinning up due to an error related to being unable to get replication controller...

Nevertheless, I do belive that the very jars related to connecting to an object storage might be of help.
