### ISSUE TITLE
Image for 2.3.1

### ISSUE THREAD

**Issue by jkremser** [radanalyticsio/openshift-spark#61]
`2.3.1` has been released on 2018-07-08

(no big changes, though)
change list: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12315420&version=12342432

**Comment by srinivas2494** [comment]
Hi,
I was using this openshift-spark along with hadoop mapr-client in it. Its working fine when I run a  docker image. I am able to connect hadoop cluster using spark-sql in separate bash terminal of running docker container.
But Iam facing issue when I am passing commands like "command:spark-sql $query" along with deployment 
Error: PFA
![screen shot 2018-10-02 at 11 40 45 am](https://user-images.githubusercontent.com/34528987/46363448-adbb4680-c638-11e8-8289-933c6bf52678.png)
Please let us know if there is solution for it

**Comment by rimolive** [comment]
Closing at this is a very old spark upgrade request.
