### ISSUE TITLE
Error when  deploying image with passing commands to it

### ISSUE THREAD

**Issue by srinivas2494** [radanalyticsio/openshift-spark#69]
Hi,
I was using this openshift-spark along with hadoop mapr-client in it. Its working fine when I run a docker image. I am able to connect hadoop cluster using spark-sql in separate bash terminal of running docker container.
But Iam facing issue when I am passing commands like "command:spark-sql $query" along with deployment
Error: PFA
![screen shot 2018-10-02 at 11 40 45 am](https://user-images.githubusercontent.com/34528987/46363579-05f24880-c639-11e8-9538-8ffb24ed91fa.png)
please let us know if there is solution for it

**Comment by elmiko** [comment]
i think we would need to know more about how you are deploying and interacting with spark. you mention docker, but this image isn't strictly targeted at running from docker. it's meant to be run on openshift.

the exception trace you are showing can happen due to a couple different reasons, knowing more about how you are deploying and running the spark driver and cluster will help diagnose the issue. can you describe your setup a little more thoroughly?

**Comment by srinivas2494** [comment]
The Intention is to run a spark job when deploying image itself. Initially I deployed a container in Openshift . and opened a terminal of running container then I did spark operation like submitting a job also do some spark-sql operation.
As next step we want to run a job itself when launching container in openshift. For that we are giving commands in yaml . In which we are facing the above  issue. we are thinking that the spark cannot identify the user  as we are passing commands from external

Issue Solved:
I think I solved the issue by changing the launch.sh script and adding spark-submit commands to it . But I don't know this solution is feasible.

**Comment by elmiko** [comment]
ok, i think i understand what you are trying to do.

in general this is not the way we have designed these images to be run, i would look at the tutorial we have on radanalytics.io that shows how to use source-to-image to deploy spark and run drivers automatically through openshift.

this https://radanalytics.io/my-first-radanalytics-app.html is a good introduction to our process and how you might build something similar.

**Comment by elmiko** [comment]
as i don't think is an error with the image, i am closing this issue.
