### ISSUE TITLE
different versions of Openshift + Jupyter

### ISSUE THREAD

**Issue by ljakob** [radanalyticsio/openshift-spark#70]
Hi,
I'm quite new in the Spark world, but I bounced into following problem:
* The Spark version in the jupyter template is 2.2, Spark is 2.3
* When I try to access the spark cluster within openshift I see serialVersionUID-errors

I tried to patch https://radanalytics.io/resources.yaml to fall back to Spark 2.2 but that didn't work.

Can you help me or update the jupyter image to spark 2.3?

Thanks

Leif

**Comment by elmiko** [comment]
hi there,

this is highlighting a gap in our tooling currently, i imagine that you are trying to connect a jupyter notebook to a spark cluster?

assuming this is the case, there are difficulties in getting spark 2.3 connected between the notebook and a spark cluster. it's probably easier to use our spark-2.2 tooling. to this you will need to use an archived copy of the resources.yaml file. this template https://github.com/radanalyticsio/radanalyticsio.github.io/blob/master/openshift/resources-v0.4.0.yaml is a previous release that still uses spark-2.2 for the oshinko tooling. the only downside here is that the manifest doesn't contain the jupyter template. so you will need to install that manually.

under the assumption that you are looking to connect the notebook to spark, you might also want to checkout this blog post that i wrote: https://elmiko.github.io/2018/08/05/attaching-notebooks-with-radanalytics.html it will walk you through the process of connecting these bits using the current release stuff.

we haven't updated the jupyter image to spark 2.3 yet, but if you wanted to experiment with changing the spark version i would recommend looking at this repo https://github.com/radanalyticsio/base-notebook . you will need to change the Dockerfile `FROM` line to use `radanalyticsio/openshift-spark:2.3-latest` as the image.

hope this helps, good luck!

**Comment by ljakob** [comment]
Hi,

thanks for the quick response. I've already patched a local version of https://github.com/radanalyticsio/base-notebook and it works (just change base-image to spark 2.3 as you suggested). Now I bounced into an other problem with the spark cluster, but that needs further investigation.

Thanks

Leif

**Comment by elmiko** [comment]
no problem, glad you figured out the host ip trick. we plan on smoothing that out but are working through a few issues. i talk a little about the notebook issue at the bottom of this blog https://elmiko.github.io/2018/05/18/python3-coming-to-radanalytics.html

**Comment by elmiko** [comment]
i'm going to close out this issue, thanks again =)
